### ISSUE TITLE
Dúvida

### ISSUE THREAD

**Issue by bartier** [andreroggeri/br-to-ynab#12]
@andreroggeri Oi, estou em dúvida se você ainda tem interesse em manter esse projeto ou se está utilizando outra gerenciador financeiro ao invés do YNAB.

Obrigado!

**Comment by andreroggeri** [comment]
Fala @bartier confesso que não tenho dado muito carinho pra esse projeto 😅

Atualmente eu tenho utilizado a branch "add-itau" para o que eu preciso.

Tem algo que não está funcionando para você ?

**Comment by bartier** [comment]
@andreroggeri A funcionalidade de importar dados do Nubank pela branch `main`. Ainda não analisei o código para ver  o erro, apenas tentei utilizar.

```bash
(venv) ➜  br-to-ynab git:(main) ✗ python brbanks2ynab/cli.py configure
[?] Qual o seu token do YNAB ?: HIDED
[?] Qual o nome do orçamento no YNAB ?: My Budget
[?] Quais bancos você irá importar os dados: 
 > o Nubank
   o Bradesco
   o Alelo

[?] A partir de qual data deseja importar as transações ? (YYYY-MM-DD): 2023-06-01
Time: 0h:00m:15s                                                                                                                                                                     
(venv) ➜  br-to-ynab git:(main) ✗ echo $?
0

```

Arquivo gerado `brbanks2ynab.json`:

```json
{
  "ynab_token": "HIDED",
  "ynab_budget": "My Budget",
  "banks": [],
  "start_import_date": "2023-06-01"
}
```

**Comment by andreroggeri** [comment]
Se eu estou vendo corretamente, você não selecionou nenhum banco, então a configuração vai ficar vazia mesmo.

Se não me engano a tecla espaço seleciona o banco que você quer e enter confirma as opções selecionadas

**Comment by bartier** [comment]
@andreroggeri É isso mesmo. Não estou acostumado com essa interface CLI 😄 

Obrigado. Irei continuar meus testes

**Comment by andreroggeri** [comment]
Talvez algumas explicações no próprio cli ajudariam 😅
