### ISSUE TITLE
Erro ao rodar sync com Nubank

### ISSUE THREAD

**Issue by klarkc** [andreroggeri/br-to-ynab#7]
Configurei para buscar transações a partir do dia anterior.

Esperava ver as transações do dia de hoje e do anterior. Não foi importado nenhuma transação.

Log com o resultado de `brbanks2ynab --debug sync`: https://pastebin.com/2zty20F1

Eu sei que não é problema de acesso porque quando executei com um range maior (um mês), as transações apareceram no YNAB (embora o mesmo erro tenha tenha ocorrido).

**Comment by andreroggeri** [comment]
Finalmente corrigido 🙈
